# Generated by Django 5.2.6 on 2025-09-27 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='grade_class',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, '1. luokka'), (2, '2. luokka'), (3, '3. luokka'), (4, '4. luokka'), (5, '5. luokka'), (6, '6. luokka'), (7, '7. luokka'), (8, '8. luokka'), (9, '9. luokka')], null=True, verbose_name='Luokka-aste'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('TEACHER', 'Teacher'), ('STUDENT', 'Student')], default='STUDENT', max_length=50),
        ),
    ]
