# Generated by Django 5.2.6 on 2025-10-17 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_grade_class_alter_customuser_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics/', verbose_name='Profiilikuva'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='grade_class',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, '1. luokka'), (2, '2. luokka'), (3, '3. luokka'), (4, '4. luokka'), (5, '5. luokka'), (6, '6. luokka')], null=True, verbose_name='Luokka-aste'),
        ),
    ]
