# Generated by Django 5.2.6 on 2025-10-21 18:20

import django.core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AIGrade',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('model_name', models.CharField(default='gpt-4o', max_length=100, verbose_name='Mallin nimi')),
                ('total_points', models.FloatField(default=0, verbose_name='Yhteispisteet')),
                ('details', models.JSONField(blank=True, default=dict, help_text="Muoto: {'criteria':[{'name','points','max','feedback'}], 'general_feedback': ''}", verbose_name='Yksityiskohdat')),
                ('teacher_confirmed', models.BooleanField(default=False, verbose_name='Opettaja vahvistanut')),
                ('teacher_notes', models.TextField(blank=True, verbose_name='Opettajan muistiinpanot')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Luotu')),
            ],
            options={
                'verbose_name': 'AI-arvio',
                'verbose_name_plural': 'AI-arviot',
            },
        ),
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('due_at', models.DateTimeField(blank=True, null=True, verbose_name='Määräaika')),
                ('status', models.CharField(choices=[('ASSIGNED', 'Annettu'), ('IN_PROGRESS', 'Kesken'), ('SUBMITTED', 'Palautettu'), ('GRADED', 'Arvioitu')], default='ASSIGNED', max_length=20, verbose_name='Tila')),
                ('draft_response', models.TextField(blank=True, null=True, verbose_name='Luonnosvastaus')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Luotu')),
            ],
            options={
                'verbose_name': 'Tehtävänanto',
                'verbose_name_plural': 'Tehtävänannot',
            },
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255, verbose_name='Otsikko')),
                ('content', models.TextField(help_text='Raakasisältö, esim. AI:n tuottama teksti.', verbose_name='Sisältö')),
                ('structured_content', models.JSONField(blank=True, help_text='Esim. monivalinnat tai tehtävän rakenne JSON-muodossa.', null=True, verbose_name='Jäsennelty sisältö')),
                ('material_type', models.CharField(choices=[('tehtävä', 'Tehtävä'), ('oppimateriaali', 'Oppimateriaali'), ('testi', 'Testi'), ('koe', 'Koe'), ('peli', 'Peli')], default='tehtävä', max_length=50, verbose_name='Materiaalin tyyppi')),
                ('subject', models.CharField(blank=True, max_length=100, null=True, verbose_name='Aine')),
                ('grade_level', models.CharField(blank=True, choices=[('1', '1. luokka'), ('2', '2. luokka'), ('3', '3. luokka'), ('4', '4. luokka'), ('5', '5. luokka'), ('6', '6. luokka')], max_length=20, null=True, verbose_name='Luokka-aste')),
                ('audience', models.JSONField(blank=True, help_text="Esim. {'learning_styles': ['visuaalinen'], 'languages': ['fi']}", null=True, verbose_name='Kohderyhmä')),
                ('status', models.CharField(choices=[('DRAFT', 'Luonnos'), ('PENDING', 'Odottaa hyväksyntää'), ('APPROVED', 'Hyväksytty'), ('REJECTED', 'Hylätty')], default='DRAFT', max_length=50, verbose_name='Tila')),
                ('version', models.IntegerField(default=1, verbose_name='Versio')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Luotu')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Päivitetty')),
            ],
            options={
                'verbose_name': 'Materiaali',
                'verbose_name_plural': 'Materiaalit',
            },
        ),
        migrations.CreateModel(
            name='MaterialImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='materials/%Y/%m/')),
                ('caption', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='MaterialRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.IntegerField(verbose_name='Versio')),
                ('note', models.CharField(blank=True, max_length=255, verbose_name='Huomio')),
                ('diff', models.JSONField(blank=True, null=True, verbose_name='Erot (diff)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Luotu')),
            ],
            options={
                'verbose_name': 'Materiaaliversio',
                'verbose_name_plural': 'Materiaaliversiot',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PlagiarismReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField(default=0.0, help_text='AI:n arvioima plagiointiriski (0–1)', verbose_name='Plagiointiriski')),
                ('highlights', models.TextField(blank=True, help_text='AI:n huomiot ja korostukset (HTML tai JSON)', verbose_name='Huomiot')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Luotu')),
            ],
            options={
                'verbose_name': 'Alkuperäisyysraportti',
                'verbose_name_plural': 'Alkuperäisyysraportit',
            },
        ),
        migrations.CreateModel(
            name='Prompt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('text', models.TextField(verbose_name='Kehoite')),
                ('model', models.CharField(max_length=100, verbose_name='Mallin tunnus')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Luotu')),
            ],
            options={
                'verbose_name': 'Kehoite',
                'verbose_name_plural': 'Kehoitteet',
            },
        ),
        migrations.CreateModel(
            name='Rubric',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(default='Oletuskriteeristö', max_length=200, verbose_name='Otsikko')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Luotu')),
            ],
            options={
                'verbose_name': 'Arviointikriteeristö',
                'verbose_name_plural': 'Arviointikriteeristöt',
            },
        ),
        migrations.CreateModel(
            name='RubricCriterion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Kriteeri')),
                ('max_points', models.PositiveIntegerField(default=5, verbose_name='Maksimipisteet')),
                ('guidance', models.TextField(blank=True, verbose_name='Ohjeistus')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Järjestys')),
            ],
            options={
                'verbose_name': 'Arviointikriteeri',
                'verbose_name_plural': 'Arviointikriteerit',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('IN_PROGRESS', 'Kesken'), ('SUBMITTED', 'Palautettu')], default='SUBMITTED', max_length=20, verbose_name='Tila')),
                ('grade', models.IntegerField(blank=True, help_text='Numeroarvosana 4–10', null=True, validators=[django.core.validators.MinValueValidator(4), django.core.validators.MaxValueValidator(10)], verbose_name='Arvosana')),
                ('score', models.DecimalField(blank=True, decimal_places=2, help_text='Saadut pisteet', max_digits=6, null=True, verbose_name='Pisteet')),
                ('max_score', models.DecimalField(blank=True, decimal_places=2, help_text='Maksimipisteet', max_digits=6, null=True, verbose_name='Maksimipisteet')),
                ('feedback', models.TextField(blank=True, help_text='Opettajan palaute', verbose_name='Palaute')),
                ('response', models.TextField(blank=True, verbose_name='Vastaus')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Luotu')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='Aloitettu')),
                ('submitted_at', models.DateTimeField(blank=True, null=True, verbose_name='Palautettu')),
                ('graded_at', models.DateTimeField(blank=True, null=True, verbose_name='Arvioitu')),
            ],
            options={
                'verbose_name': 'Palautus',
                'verbose_name_plural': 'Palautukset',
            },
        ),
    ]
