# Generated by Django 5.2.6 on 2025-10-21 17:44

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255, verbose_name='Otsikko')),
                ('content', models.TextField(help_text='Raakasisältö, esim. AI:n tuottama teksti.', verbose_name='Sisältö')),
                ('structured_content', models.JSONField(blank=True, help_text='Esim. monivalinnat tai tehtävän rakenne JSON-muodossa.', null=True, verbose_name='Jäsennelty sisältö')),
                ('material_type', models.CharField(choices=[('tehtävä', 'Tehtävä'), ('oppimateriaali', 'Oppimateriaali'), ('testi', 'Testi'), ('koe', 'Koe'), ('peli', 'Peli')], default='tehtävä', max_length=50, verbose_name='Materiaalin tyyppi')),
                ('subject', models.CharField(blank=True, max_length=100, null=True, verbose_name='Aine')),
                ('grade_level', models.CharField(blank=True, choices=[('1', '1. luokka'), ('2', '2. luokka'), ('3', '3. luokka'), ('4', '4. luokka'), ('5', '5. luokka'), ('6', '6. luokka')], max_length=20, null=True, verbose_name='Luokka-aste')),
                ('audience', models.JSONField(blank=True, help_text="Esim. {'learning_styles': ['visuaalinen'], 'languages': ['fi']}", null=True, verbose_name='Kohderyhmä')),
                ('status', models.CharField(choices=[('DRAFT', 'Luonnos'), ('PENDING', 'Odottaa hyväksyntää'), ('APPROVED', 'Hyväksytty'), ('REJECTED', 'Hylätty')], default='DRAFT', max_length=50, verbose_name='Tila')),
                ('version', models.IntegerField(default=1, verbose_name='Versio')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Luotu')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Päivitetty')),
                ('author', models.ForeignKey(limit_choices_to={'role': 'TEACHER'}, on_delete=django.db.models.deletion.CASCADE, related_name='authored_materials', to=settings.AUTH_USER_MODEL, verbose_name='Tekijä (opettaja)')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='versions', to='materials.material', verbose_name='Edellinen versio')),
            ],
            options={
                'verbose_name': 'Materiaali',
                'verbose_name_plural': 'Materiaalit',
            },
        ),
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('due_at', models.DateTimeField(blank=True, null=True, verbose_name='Määräaika')),
                ('status', models.CharField(choices=[('ASSIGNED', 'Annettu'), ('IN_PROGRESS', 'Kesken'), ('SUBMITTED', 'Palautettu'), ('GRADED', 'Arvioitu')], default='ASSIGNED', max_length=20, verbose_name='Tila')),
                ('draft_response', models.TextField(blank=True, null=True, verbose_name='Luonnosvastaus')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Luotu')),
                ('assigned_by', models.ForeignKey(limit_choices_to={'role': 'TEACHER'}, on_delete=django.db.models.deletion.CASCADE, related_name='assigned_tasks', to=settings.AUTH_USER_MODEL, verbose_name='Antanut opettaja')),
                ('student', models.ForeignKey(limit_choices_to={'role': 'STUDENT'}, on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to=settings.AUTH_USER_MODEL, verbose_name='Oppilas')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='materials.material', verbose_name='Materiaali')),
            ],
            options={
                'verbose_name': 'Tehtävänanto',
                'verbose_name_plural': 'Tehtävänannot',
            },
        ),
        migrations.CreateModel(
            name='MaterialImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='materials/%Y/%m/')),
                ('caption', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='materials.material')),
            ],
        ),
        migrations.CreateModel(
            name='MaterialRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.IntegerField(verbose_name='Versio')),
                ('note', models.CharField(blank=True, max_length=255, verbose_name='Huomio')),
                ('diff', models.JSONField(blank=True, null=True, verbose_name='Erot (diff)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Luotu')),
                ('editor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Muokkaaja')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='materials.material', verbose_name='Materiaali')),
            ],
            options={
                'verbose_name': 'Materiaaliversio',
                'verbose_name_plural': 'Materiaaliversiot',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Prompt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('text', models.TextField(verbose_name='Kehoite')),
                ('model', models.CharField(max_length=100, verbose_name='Mallin tunnus')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Luotu')),
                ('teacher', models.ForeignKey(limit_choices_to={'role': 'TEACHER'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Opettaja')),
            ],
            options={
                'verbose_name': 'Kehoite',
                'verbose_name_plural': 'Kehoitteet',
            },
        ),
        migrations.AddField(
            model_name='material',
            name='prompt',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='materials.prompt', verbose_name='Kehoite'),
        ),
        migrations.CreateModel(
            name='Rubric',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(default='Oletuskriteeristö', max_length=200, verbose_name='Otsikko')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Luotu')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Luonut')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rubrics', to='materials.material', verbose_name='Materiaali')),
            ],
            options={
                'verbose_name': 'Arviointikriteeristö',
                'verbose_name_plural': 'Arviointikriteeristöt',
            },
        ),
        migrations.CreateModel(
            name='RubricCriterion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Kriteeri')),
                ('max_points', models.PositiveIntegerField(default=5, verbose_name='Maksimipisteet')),
                ('guidance', models.TextField(blank=True, verbose_name='Ohjeistus')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Järjestys')),
                ('rubric', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='criteria', to='materials.rubric', verbose_name='Kriteeristö')),
            ],
            options={
                'verbose_name': 'Arviointikriteeri',
                'verbose_name_plural': 'Arviointikriteerit',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('IN_PROGRESS', 'Kesken'), ('SUBMITTED', 'Palautettu')], default='SUBMITTED', max_length=20, verbose_name='Tila')),
                ('grade', models.IntegerField(blank=True, help_text='Numeroarvosana 4–10', null=True, validators=[django.core.validators.MinValueValidator(4), django.core.validators.MaxValueValidator(10)], verbose_name='Arvosana')),
                ('score', models.DecimalField(blank=True, decimal_places=2, help_text='Saadut pisteet', max_digits=6, null=True, verbose_name='Pisteet')),
                ('max_score', models.DecimalField(blank=True, decimal_places=2, help_text='Maksimipisteet', max_digits=6, null=True, verbose_name='Maksimipisteet')),
                ('feedback', models.TextField(blank=True, help_text='Opettajan palaute', verbose_name='Palaute')),
                ('response', models.TextField(blank=True, verbose_name='Vastaus')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Luotu')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='Aloitettu')),
                ('submitted_at', models.DateTimeField(blank=True, null=True, verbose_name='Palautettu')),
                ('graded_at', models.DateTimeField(blank=True, null=True, verbose_name='Arvioitu')),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='materials.assignment', verbose_name='Tehtävänanto')),
                ('student', models.ForeignKey(limit_choices_to={'role': 'STUDENT'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Oppilas')),
            ],
            options={
                'verbose_name': 'Palautus',
                'verbose_name_plural': 'Palautukset',
            },
        ),
        migrations.CreateModel(
            name='PlagiarismReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField(default=0.0, help_text='AI:n arvioima plagiointiriski (0–1)', verbose_name='Plagiointiriski')),
                ('highlights', models.TextField(blank=True, help_text='AI:n huomiot ja korostukset (HTML tai JSON)', verbose_name='Huomiot')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Luotu')),
                ('submission', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='plagiarism_report', to='materials.submission', verbose_name='Palautus')),
                ('suspected_source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plagiarized_by', to='materials.submission', verbose_name='Mahdollinen lähde')),
            ],
            options={
                'verbose_name': 'Alkuperäisyysraportti',
                'verbose_name_plural': 'Alkuperäisyysraportit',
            },
        ),
        migrations.CreateModel(
            name='AIGrade',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('model_name', models.CharField(default='gpt-4o', max_length=100, verbose_name='Mallin nimi')),
                ('total_points', models.FloatField(default=0, verbose_name='Yhteispisteet')),
                ('details', models.JSONField(blank=True, default=dict, help_text="Muoto: {'criteria':[{'name','points','max','feedback'}], 'general_feedback': ''}", verbose_name='Yksityiskohdat')),
                ('teacher_confirmed', models.BooleanField(default=False, verbose_name='Opettaja vahvistanut')),
                ('teacher_notes', models.TextField(blank=True, verbose_name='Opettajan muistiinpanot')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Luotu')),
                ('rubric', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='materials.rubric', verbose_name='Kriteeristö')),
                ('submission', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ai_grade', to='materials.submission', verbose_name='Palautus')),
            ],
            options={
                'verbose_name': 'AI-arvio',
                'verbose_name_plural': 'AI-arviot',
            },
        ),
        migrations.AddIndex(
            model_name='assignment',
            index=models.Index(fields=['status'], name='materials_a_status_fd49d1_idx'),
        ),
        migrations.AddIndex(
            model_name='assignment',
            index=models.Index(fields=['due_at'], name='materials_a_due_at_37a65f_idx'),
        ),
        migrations.AddIndex(
            model_name='assignment',
            index=models.Index(fields=['student'], name='materials_a_student_412d80_idx'),
        ),
        migrations.AddIndex(
            model_name='assignment',
            index=models.Index(fields=['assigned_by'], name='materials_a_assigne_c96fdb_idx'),
        ),
        migrations.AddConstraint(
            model_name='assignment',
            constraint=models.UniqueConstraint(fields=('material', 'student'), name='unique_assignment_per_student'),
        ),
    ]
