# Generated by Django 5.2.6 on 2025-09-04 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField(help_text='The main content, or a description for the material.')),
                ('material_type', models.CharField(choices=[('QUIZ', 'Quiz'), ('GAME', 'Game'), ('IMAGE', 'Image'), ('VIDEO', 'Video')], max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
