# Generated by Django 5.2.6 on 2025-10-21 18:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('materials', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='assigned_by',
            field=models.ForeignKey(limit_choices_to={'role': 'TEACHER'}, on_delete=django.db.models.deletion.CASCADE, related_name='assigned_tasks', to=settings.AUTH_USER_MODEL, verbose_name='Antanut opettaja'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='student',
            field=models.ForeignKey(limit_choices_to={'role': 'STUDENT'}, on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to=settings.AUTH_USER_MODEL, verbose_name='Oppilas'),
        ),
        migrations.AddField(
            model_name='material',
            name='author',
            field=models.ForeignKey(limit_choices_to={'role': 'TEACHER'}, on_delete=django.db.models.deletion.CASCADE, related_name='authored_materials', to=settings.AUTH_USER_MODEL, verbose_name='Tekijä (opettaja)'),
        ),
        migrations.AddField(
            model_name='material',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='versions', to='materials.material', verbose_name='Edellinen versio'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='materials.material', verbose_name='Materiaali'),
        ),
        migrations.AddField(
            model_name='materialimage',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='materialimage',
            name='material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='materials.material'),
        ),
        migrations.AddField(
            model_name='materialrevision',
            name='editor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Muokkaaja'),
        ),
        migrations.AddField(
            model_name='materialrevision',
            name='material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='materials.material', verbose_name='Materiaali'),
        ),
        migrations.AddField(
            model_name='prompt',
            name='teacher',
            field=models.ForeignKey(limit_choices_to={'role': 'TEACHER'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Opettaja'),
        ),
        migrations.AddField(
            model_name='material',
            name='prompt',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='materials.prompt', verbose_name='Kehoite'),
        ),
        migrations.AddField(
            model_name='rubric',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Luonut'),
        ),
        migrations.AddField(
            model_name='rubric',
            name='material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rubrics', to='materials.material', verbose_name='Materiaali'),
        ),
        migrations.AddField(
            model_name='aigrade',
            name='rubric',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='materials.rubric', verbose_name='Kriteeristö'),
        ),
        migrations.AddField(
            model_name='rubriccriterion',
            name='rubric',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='criteria', to='materials.rubric', verbose_name='Kriteeristö'),
        ),
        migrations.AddField(
            model_name='submission',
            name='assignment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='materials.assignment', verbose_name='Tehtävänanto'),
        ),
        migrations.AddField(
            model_name='submission',
            name='student',
            field=models.ForeignKey(limit_choices_to={'role': 'STUDENT'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Oppilas'),
        ),
        migrations.AddField(
            model_name='plagiarismreport',
            name='submission',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='plagiarism_report', to='materials.submission', verbose_name='Palautus'),
        ),
        migrations.AddField(
            model_name='plagiarismreport',
            name='suspected_source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plagiarized_by', to='materials.submission', verbose_name='Mahdollinen lähde'),
        ),
        migrations.AddField(
            model_name='aigrade',
            name='submission',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ai_grade', to='materials.submission', verbose_name='Palautus'),
        ),
        migrations.AddIndex(
            model_name='assignment',
            index=models.Index(fields=['status'], name='materials_a_status_fd49d1_idx'),
        ),
        migrations.AddIndex(
            model_name='assignment',
            index=models.Index(fields=['due_at'], name='materials_a_due_at_37a65f_idx'),
        ),
        migrations.AddIndex(
            model_name='assignment',
            index=models.Index(fields=['student'], name='materials_a_student_412d80_idx'),
        ),
        migrations.AddIndex(
            model_name='assignment',
            index=models.Index(fields=['assigned_by'], name='materials_a_assigne_c96fdb_idx'),
        ),
        migrations.AddConstraint(
            model_name='assignment',
            constraint=models.UniqueConstraint(fields=('material', 'student'), name='unique_assignment_per_student'),
        ),
    ]
