# Generated by Django 5.2.6 on 2025-09-11 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0003_material_audience_material_grade_level_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='draft_response',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='status',
            field=models.CharField(choices=[('ASSIGNED', 'Assigned'), ('IN_PROGRESS', 'In Progress'), ('SUBMITTED', 'Submitted'), ('GRADED', 'Graded'), ('RETURNED', 'Returned')], default='ASSIGNED', max_length=50),
        ),
    ]
