# Generated by Django 5.2.6 on 2025-09-12 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0004_assignment_draft_response_alter_assignment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='material_type',
            field=models.CharField(choices=[('QUIZ', 'Kysely'), ('GAME', 'Peli'), ('IMAGE', 'Kuva'), ('VIDEO', 'Video'), ('LESSON', 'Oppitunti')], max_length=50),
        ),
    ]
