# Generated by Django 5.2.6 on 2025-09-12 14:41

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0005_alter_material_material_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='submission',
            name='graded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='status',
            field=models.CharField(choices=[('ASSIGNED', 'Annettu'), ('IN_PROGRESS', 'Kesken'), ('SUBMITTED', 'Palautettu'), ('GRADED', 'Arvioitu')], default='ASSIGNED', max_length=50),
        ),
        migrations.AlterField(
            model_name='submission',
            name='response',
            field=models.TextField(blank=True, default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='submission',
            name='status',
            field=models.CharField(choices=[('IN_PROGRESS', 'Kesken'), ('SUBMITTED', 'Palautettu')], default='SUBMITTED', max_length=20),
        ),
    ]
