# Generated by Django 5.2.6 on 2025-09-12 15:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0006_submission_created_at_submission_graded_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='grade',
            field=models.IntegerField(blank=True, help_text='Numeroarvosana 4–10', null=True, validators=[django.core.validators.MinValueValidator(4), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AddField(
            model_name='submission',
            name='max_score',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Maksimipisteet', max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='submission',
            name='feedback',
            field=models.TextField(blank=True, help_text='Opettajan palaute'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='score',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Saadut pisteet', max_digits=6, null=True),
        ),
    ]
