# Generated by Django 5.2.6 on 2025-09-17 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0007_submission_grade_submission_max_score_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='grade_level',
            field=models.CharField(blank=True, choices=[('1', '1. luokka'), ('2', '2. luokka'), ('3', '3. luokka'), ('4', '4. luokka'), ('5', '5. luokka'), ('6', '6. luokka'), ('7', '7. luokka'), ('8', '8. luokka'), ('9', '9. luokka')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='material',
            name='material_type',
            field=models.CharField(choices=[('tehtävä', 'Tehtävä'), ('oppimateriaali', 'Oppimateriaali'), ('testi', 'Testi'), ('koe', 'Koe'), ('video', 'Video'), ('peli', 'Peli')], default='tehtävä', max_length=50),
        ),
    ]
