# Generated by Django 5.2.6 on 2025-09-19 07:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0008_alter_material_grade_level_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='status',
            field=models.CharField(choices=[('ASSIGNED', 'Annettu'), ('IN_PROGRESS', 'Kesken'), ('SUBMITTED', 'Palautettu'), ('GRADED', 'Arvioitu')], default='ASSIGNED', max_length=20),
        ),
        migrations.AddIndex(
            model_name='assignment',
            index=models.Index(fields=['status'], name='materials_a_status_fd49d1_idx'),
        ),
        migrations.AddIndex(
            model_name='assignment',
            index=models.Index(fields=['due_at'], name='materials_a_due_at_37a65f_idx'),
        ),
        migrations.AddIndex(
            model_name='assignment',
            index=models.Index(fields=['student'], name='materials_a_student_412d80_idx'),
        ),
        migrations.AddIndex(
            model_name='assignment',
            index=models.Index(fields=['assigned_by'], name='materials_a_assigne_c96fdb_idx'),
        ),
        migrations.AddConstraint(
            model_name='assignment',
            constraint=models.UniqueConstraint(fields=('material', 'student'), name='unique_assignment_per_student'),
        ),
    ]
