# Generated by Django 5.1.7 on 2025-09-25 06:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0009_alter_assignment_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlagiarismReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField(default=0.0, help_text='Cosine similarity score between submissions')),
                ('highlights', models.TextField(blank=True, help_text='Highlighted overlapping text segments in HTML or JSON format')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('submission', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='plagiarism_report', to='materials.submission')),
                ('suspected_source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plagiarized_by', to='materials.submission')),
            ],
        ),
    ]
