# Generated by Django 5.1.7 on 2025-09-26 06:11

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0011_rubric_aigrade_rubriccriterion'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aigrade',
            options={'verbose_name': 'AI-arvio', 'verbose_name_plural': 'AI-arviot'},
        ),
        migrations.AlterModelOptions(
            name='assignment',
            options={'verbose_name': 'Tehtävänanto', 'verbose_name_plural': 'Tehtävänannot'},
        ),
        migrations.AlterModelOptions(
            name='material',
            options={'verbose_name': 'Materiaali', 'verbose_name_plural': 'Materiaalit'},
        ),
        migrations.AlterModelOptions(
            name='materialrevision',
            options={'ordering': ['-created_at'], 'verbose_name': 'Materiaaliversio', 'verbose_name_plural': 'Materiaaliversiot'},
        ),
        migrations.AlterModelOptions(
            name='plagiarismreport',
            options={'verbose_name': 'Alkuperäisyysraportti', 'verbose_name_plural': 'Alkuperäisyysraportit'},
        ),
        migrations.AlterModelOptions(
            name='prompt',
            options={'verbose_name': 'Kehoite', 'verbose_name_plural': 'Kehoitteet'},
        ),
        migrations.AlterModelOptions(
            name='rubric',
            options={'verbose_name': 'Arviointikriteeristö', 'verbose_name_plural': 'Arviointikriteeristöt'},
        ),
        migrations.AlterModelOptions(
            name='rubriccriterion',
            options={'ordering': ['order', 'id'], 'verbose_name': 'Arviointikriteeri', 'verbose_name_plural': 'Arviointikriteerit'},
        ),
        migrations.AlterModelOptions(
            name='submission',
            options={'verbose_name': 'Palautus', 'verbose_name_plural': 'Palautukset'},
        ),
        migrations.AlterField(
            model_name='aigrade',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Luotu'),
        ),
        migrations.AlterField(
            model_name='aigrade',
            name='details',
            field=models.JSONField(blank=True, default=dict, help_text="Muoto: {'criteria':[{'name','points','max','feedback'}], 'general_feedback': ''}", verbose_name='Yksityiskohdat'),
        ),
        migrations.AlterField(
            model_name='aigrade',
            name='model_name',
            field=models.CharField(default='gpt-4o', max_length=100, verbose_name='Mallin nimi'),
        ),
        migrations.AlterField(
            model_name='aigrade',
            name='rubric',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='materials.rubric', verbose_name='Kriteeristö'),
        ),
        migrations.AlterField(
            model_name='aigrade',
            name='submission',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ai_grade', to='materials.submission', verbose_name='Palautus'),
        ),
        migrations.AlterField(
            model_name='aigrade',
            name='teacher_confirmed',
            field=models.BooleanField(default=False, verbose_name='Opettaja vahvistanut'),
        ),
        migrations.AlterField(
            model_name='aigrade',
            name='teacher_notes',
            field=models.TextField(blank=True, verbose_name='Opettajan muistiinpanot'),
        ),
        migrations.AlterField(
            model_name='aigrade',
            name='total_points',
            field=models.FloatField(default=0, verbose_name='Yhteispisteet'),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='assigned_by',
            field=models.ForeignKey(limit_choices_to={'role': 'TEACHER'}, on_delete=django.db.models.deletion.CASCADE, related_name='assigned_tasks', to=settings.AUTH_USER_MODEL, verbose_name='Antanut opettaja'),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Luotu'),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='draft_response',
            field=models.TextField(blank=True, null=True, verbose_name='Luonnosvastaus'),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='due_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Määräaika'),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='materials.material', verbose_name='Materiaali'),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='status',
            field=models.CharField(choices=[('ASSIGNED', 'Annettu'), ('IN_PROGRESS', 'Kesken'), ('SUBMITTED', 'Palautettu'), ('GRADED', 'Arvioitu')], default='ASSIGNED', max_length=20, verbose_name='Tila'),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='student',
            field=models.ForeignKey(limit_choices_to={'role': 'STUDENT'}, on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to=settings.AUTH_USER_MODEL, verbose_name='Oppilas'),
        ),
        migrations.AlterField(
            model_name='material',
            name='audience',
            field=models.JSONField(blank=True, help_text="Esim. {'learning_styles': ['visuaalinen'], 'languages': ['fi']}", null=True, verbose_name='Kohderyhmä'),
        ),
        migrations.AlterField(
            model_name='material',
            name='author',
            field=models.ForeignKey(limit_choices_to={'role': 'TEACHER'}, on_delete=django.db.models.deletion.CASCADE, related_name='authored_materials', to=settings.AUTH_USER_MODEL, verbose_name='Tekijä (opettaja)'),
        ),
        migrations.AlterField(
            model_name='material',
            name='content',
            field=models.TextField(help_text='Raakasisältö, esim. AI:n tuottama teksti.', verbose_name='Sisältö'),
        ),
        migrations.AlterField(
            model_name='material',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Luotu'),
        ),
        migrations.AlterField(
            model_name='material',
            name='grade_level',
            field=models.CharField(blank=True, choices=[('1', '1. luokka'), ('2', '2. luokka'), ('3', '3. luokka'), ('4', '4. luokka'), ('5', '5. luokka'), ('6', '6. luokka'), ('7', '7. luokka'), ('8', '8. luokka'), ('9', '9. luokka')], max_length=20, null=True, verbose_name='Luokka-aste'),
        ),
        migrations.AlterField(
            model_name='material',
            name='material_type',
            field=models.CharField(choices=[('tehtävä', 'Tehtävä'), ('oppimateriaali', 'Oppimateriaali'), ('testi', 'Testi'), ('koe', 'Koe'), ('video', 'Video'), ('peli', 'Peli')], default='tehtävä', max_length=50, verbose_name='Materiaalin tyyppi'),
        ),
        migrations.AlterField(
            model_name='material',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='versions', to='materials.material', verbose_name='Edellinen versio'),
        ),
        migrations.AlterField(
            model_name='material',
            name='prompt',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='materials.prompt', verbose_name='Kehoite'),
        ),
        migrations.AlterField(
            model_name='material',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Luonnos'), ('PENDING', 'Odottaa hyväksyntää'), ('APPROVED', 'Hyväksytty'), ('REJECTED', 'Hylätty')], default='DRAFT', max_length=50, verbose_name='Tila'),
        ),
        migrations.AlterField(
            model_name='material',
            name='structured_content',
            field=models.JSONField(blank=True, help_text='Esim. monivalinnat tai tehtävän rakenne JSON-muodossa.', null=True, verbose_name='Jäsennelty sisältö'),
        ),
        migrations.AlterField(
            model_name='material',
            name='subject',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Aine'),
        ),
        migrations.AlterField(
            model_name='material',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Otsikko'),
        ),
        migrations.AlterField(
            model_name='material',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Päivitetty'),
        ),
        migrations.AlterField(
            model_name='material',
            name='version',
            field=models.IntegerField(default=1, verbose_name='Versio'),
        ),
        migrations.AlterField(
            model_name='materialrevision',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Luotu'),
        ),
        migrations.AlterField(
            model_name='materialrevision',
            name='diff',
            field=models.JSONField(blank=True, null=True, verbose_name='Erot (diff)'),
        ),
        migrations.AlterField(
            model_name='materialrevision',
            name='editor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Muokkaaja'),
        ),
        migrations.AlterField(
            model_name='materialrevision',
            name='material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='materials.material', verbose_name='Materiaali'),
        ),
        migrations.AlterField(
            model_name='materialrevision',
            name='note',
            field=models.CharField(blank=True, max_length=255, verbose_name='Huomio'),
        ),
        migrations.AlterField(
            model_name='materialrevision',
            name='version',
            field=models.IntegerField(verbose_name='Versio'),
        ),
        migrations.AlterField(
            model_name='plagiarismreport',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Luotu'),
        ),
        migrations.AlterField(
            model_name='plagiarismreport',
            name='highlights',
            field=models.TextField(blank=True, help_text='AI:n huomiot ja korostukset (HTML tai JSON)', verbose_name='Huomiot'),
        ),
        migrations.AlterField(
            model_name='plagiarismreport',
            name='score',
            field=models.FloatField(default=0.0, help_text='AI:n arvioima plagiointiriski (0–1)', verbose_name='Plagiointiriski'),
        ),
        migrations.AlterField(
            model_name='plagiarismreport',
            name='submission',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='plagiarism_report', to='materials.submission', verbose_name='Palautus'),
        ),
        migrations.AlterField(
            model_name='plagiarismreport',
            name='suspected_source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plagiarized_by', to='materials.submission', verbose_name='Mahdollinen lähde'),
        ),
        migrations.AlterField(
            model_name='prompt',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Luotu'),
        ),
        migrations.AlterField(
            model_name='prompt',
            name='model',
            field=models.CharField(max_length=100, verbose_name='Mallin tunnus'),
        ),
        migrations.AlterField(
            model_name='prompt',
            name='teacher',
            field=models.ForeignKey(limit_choices_to={'role': 'TEACHER'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Opettaja'),
        ),
        migrations.AlterField(
            model_name='prompt',
            name='text',
            field=models.TextField(verbose_name='Kehoite'),
        ),
        migrations.AlterField(
            model_name='rubric',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Luotu'),
        ),
        migrations.AlterField(
            model_name='rubric',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Luonut'),
        ),
        migrations.AlterField(
            model_name='rubric',
            name='material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rubrics', to='materials.material', verbose_name='Materiaali'),
        ),
        migrations.AlterField(
            model_name='rubric',
            name='title',
            field=models.CharField(default='Oletuskriteeristö', max_length=200, verbose_name='Otsikko'),
        ),
        migrations.AlterField(
            model_name='rubriccriterion',
            name='guidance',
            field=models.TextField(blank=True, verbose_name='Ohjeistus'),
        ),
        migrations.AlterField(
            model_name='rubriccriterion',
            name='max_points',
            field=models.PositiveIntegerField(default=5, verbose_name='Maksimipisteet'),
        ),
        migrations.AlterField(
            model_name='rubriccriterion',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Kriteeri'),
        ),
        migrations.AlterField(
            model_name='rubriccriterion',
            name='order',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Järjestys'),
        ),
        migrations.AlterField(
            model_name='rubriccriterion',
            name='rubric',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='criteria', to='materials.rubric', verbose_name='Kriteeristö'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='assignment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='materials.assignment', verbose_name='Tehtävänanto'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Luotu'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='feedback',
            field=models.TextField(blank=True, help_text='Opettajan palaute', verbose_name='Palaute'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='grade',
            field=models.IntegerField(blank=True, help_text='Numeroarvosana 4–10', null=True, validators=[django.core.validators.MinValueValidator(4), django.core.validators.MaxValueValidator(10)], verbose_name='Arvosana'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='graded_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Arvioitu'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='max_score',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Maksimipisteet', max_digits=6, null=True, verbose_name='Maksimipisteet'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='response',
            field=models.TextField(blank=True, verbose_name='Vastaus'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='score',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Saadut pisteet', max_digits=6, null=True, verbose_name='Pisteet'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='started_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Aloitettu'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='status',
            field=models.CharField(choices=[('IN_PROGRESS', 'Kesken'), ('SUBMITTED', 'Palautettu')], default='SUBMITTED', max_length=20, verbose_name='Tila'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='student',
            field=models.ForeignKey(limit_choices_to={'role': 'STUDENT'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Oppilas'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='submitted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Palautettu'),
        ),
    ]
