# Generated by Django 5.2 on 2025-10-04 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0013_materialimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='grade_level',
            field=models.CharField(blank=True, choices=[('1', '1. luokka'), ('2', '2. luokka'), ('3', '3. luokka'), ('4', '4. luokka'), ('5', '5. luokka'), ('6', '6. luokka')], max_length=20, null=True, verbose_name='Luokka-aste'),
        ),
    ]
