# Generated by Django 5.2.6 on 2025-10-17 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0014_alter_material_grade_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='material_type',
            field=models.CharField(choices=[('tehtävä', 'Tehtävä'), ('oppimateriaali', 'Oppimateriaali'), ('testi', 'Testi'), ('koe', 'Koe'), ('peli', 'Peli')], default='tehtävä', max_length=50, verbose_name='Materiaalin tyyppi'),
        ),
    ]
