# materials/models.py
import uuid
from django.db import models
from django.conf import settings
from django.utils.translation import gettext_lazy as _
import uuid
from django.core.validators import MinValueValidator, MaxValueValidator

class Prompt(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    text = models.TextField()
    model = models.CharField(max_length=100)
    teacher = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        limit_choices_to={'role': 'TEACHER'}
    )
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"Prompt by {self.teacher.username} at {self.created_at.strftime('%Y-%m-%d')}"

class Material(models.Model):
    class MaterialType(models.TextChoices):
        QUIZ = 'QUIZ', 'Kysely'
        GAME = 'GAME', 'Peli'
        IMAGE = 'IMAGE', 'Kuva'
        VIDEO = 'VIDEO', 'Video'
        LESSON = 'LESSON', 'Oppitunti'

    class Status(models.TextChoices):
        DRAFT = 'DRAFT', 'Draft'
        PENDING_APPROVAL = 'PENDING', 'Pending Approval'
        APPROVED = 'APPROVED', 'Approved'
        REJECTED = 'REJECTED', 'Rejected'

    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    title = models.CharField(max_length=255)
    content = models.TextField(help_text="The raw content generated by the AI.")
    structured_content = models.JSONField(null=True, blank=True, help_text="Parsed content, e.g., quiz questions.")
    material_type = models.CharField(max_length=50, choices=MaterialType.choices)
    subject = models.CharField(max_length=100, null=True, blank=True)
    grade_level = models.IntegerField(null=True, blank=True)
    audience = models.JSONField(null=True, blank=True, help_text="e.g., {'learning_styles': ['visual'], 'languages': ['en', 'fi']}")
    
    author = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        related_name='authored_materials',
        on_delete=models.CASCADE,
        limit_choices_to={'role': 'TEACHER'}
    )
    prompt = models.ForeignKey(Prompt, on_delete=models.SET_NULL, null=True, blank=True)
    status = models.CharField(max_length=50, choices=Status.choices, default=Status.DRAFT)
    version = models.IntegerField(default=1)
    parent = models.ForeignKey('self', on_delete=models.SET_NULL, null=True, blank=True, related_name='versions')
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f"{self.title} (v{self.version})"

class MaterialRevision(models.Model):
    material = models.ForeignKey(Material, on_delete=models.CASCADE, related_name='revisions')
    version = models.IntegerField()
    editor = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.SET_NULL, null=True)
    note = models.CharField(max_length=255, blank=True)
    diff = models.JSONField(null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ['-created_at']

# ==========================================================
# --- MODIFICATIONS START HERE ---
# ==========================================================
class Assignment(models.Model):
    class Status(models.TextChoices):
        ASSIGNED     = "ASSIGNED",     _("Annettu")
        IN_PROGRESS  = "IN_PROGRESS",  _("Kesken")
        SUBMITTED    = "SUBMITTED",    _("Palautettu")
        GRADED       = "GRADED",       _("Arvioitu")

    status = models.CharField(
        max_length=20,
        choices=Status.choices,
        default=Status.ASSIGNED,
    )

    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    material = models.ForeignKey(Material, on_delete=models.CASCADE)
    student = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        related_name='assignments',
        on_delete=models.CASCADE,
        limit_choices_to={'role': 'STUDENT'}
    )
    assigned_by = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        related_name='assigned_tasks',
        on_delete=models.CASCADE,
        limit_choices_to={'role': 'TEACHER'}
    )
    due_at = models.DateTimeField(null=True, blank=True)
    status = models.CharField(max_length=50, choices=Status.choices, default=Status.ASSIGNED)
    
    # This new field will store the student's saved work before final submission.
    draft_response = models.TextField(blank=True, null=True) # <-- 2. ADD THIS NEW FIELD
    
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"'{self.material.title}' for {self.student.username}"
# ==========================================================
# --- MODIFICATIONS END HERE ---
# ==========================================================

class Submission(models.Model):
    class Status(models.TextChoices):
        IN_PROGRESS = 'IN_PROGRESS', 'Kesken'
        SUBMITTED   = 'SUBMITTED',   'Palautettu'

    id = models.UUIDField(
        primary_key=True,
        default=uuid.uuid4,
        editable=False
    )

    assignment = models.ForeignKey(
        'materials.Assignment',
        on_delete=models.CASCADE,
        related_name='submissions'
    )
    student = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        limit_choices_to={'role': 'STUDENT'}
    )

    status = models.CharField(
        max_length=20,
        choices=Status.choices,
        default=Status.SUBMITTED
    )

    # Numeroarvosana 4–10 (suomalainen asteikko)
    grade = models.IntegerField(
        null=True,
        blank=True,
        validators=[MinValueValidator(4), MaxValueValidator(10)],
        help_text="Numeroarvosana 4–10"
    )

    # Pisteet (esim. 17.0 / 20.0)
    score = models.DecimalField(
        max_digits=6,
        decimal_places=2,
        null=True,
        blank=True,
        help_text="Saadut pisteet"
    )
    max_score = models.DecimalField(
        max_digits=6,
        decimal_places=2,
        null=True,
        blank=True,
        help_text="Maksimipisteet"
    )

    feedback = models.TextField(
        blank=True,
        help_text="Opettajan palaute"
    )

    # Oppilaan kirjoittama vastaus
    response = models.TextField(blank=True)

    # Aikaleimat
    created_at = models.DateTimeField(auto_now_add=True)
    started_at = models.DateTimeField(auto_now_add=True)
    submitted_at = models.DateTimeField(null=True, blank=True)
    graded_at = models.DateTimeField(null=True, blank=True)

    def __str__(self):
        return f"{self.student} → {self.assignment} ({self.get_status_display()})"